version: '3'

services: 
  db:
   image: postgres:14
   container_name: bills_db
   restart: always
   environment:
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_DB: ${DB_NAME}
   ports: 
    - 3031:5432 
   volumes: 
    - ./data:/var/lib/postgresql/data

  db_e2e:
   image: postgres:14
   container_name: bills_db_e2e
   environment:
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_DB: ${DB_NAME_E2E}
   ports:
   - 3032:5432 
     

  pgadmin: 
   image: dpage/pgadmin4
   environment:
    PGADMIN_DEFAULT_EMAIL: admin@gmail.com
    PGADMIN_DEFAULT_PASSWORD: root
   ports: 
    - 5050:80  